scst_lib,scst_sysfs: Add aen_disabled setting
SCST-project/scst pull request #141
Opened 2023-03-23 23:55 UTC by bmeagherix

Add a setting to `scst_tgt` that can prevent `scst_gen_aen_or_ua` from generating an AEN, even if the underlying transport is capable of transmitting them.  It will instead generate a UA.

This could prove useful in different situations, including when the target is also a _forward_dst_.

(The new _sysfs_ interface was modeled on the code for _forward_dst_.)

2023-04-11 07:17 UTC, lnocturno commented
Hi Brian,

Sorry for the long response, but I still need more time to review your patch.
I'm trying to get it done by the end of this week.

Thanks,
Gleb

2023-04-12 07:50 UTC, lnocturno commented
Hi Brian,

> FWIW, as you may notice the new checkpatch requirement means that some code doesn't match the rest of the codebase

The idea behind the new checkpatch requirement is to check new patches for errors/warnings. The current codebase still contains a lot of checkpatch errors/warnings, but I think I will fix them step by step wherever possible.

Not every error/warning needs to be fixed, I have already added an ignore rule for some of them and will continue to do so, depending on the type. In your case, you did everything right:

https://lkml.org/lkml/2021/9/4/55
https://lore.kernel.org/lkml/CA+55aFw5v23T-zvDZp-MmD_EYxF8WbafwwB59934FV7g21uMGQ@mail.gmail.com/

2023-04-17 14:39 UTC, lnocturno requested changes

2023-04-17 15:59 UTC, bmeagherix commented
BTW, this PR deliberately does **not** include suppressing AENs from `scst_report_luns_changed_sess` ... less obviously useful to do so there.

2023-04-17 17:31 UTC, lnocturno approved these changes

2023-04-17 17:31 UTC, merged

2023-04-17 17:32 UTC, lnocturno commented
Hi Brian,

Thank you for the patch!

Thanks,
Gleb